### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by MotorSportF1** [geek1011/BookBrowser#28]
Isn't a bug.

I want to install this on my FreeBSD system but I have error when launch the program:
go build bookbrowser.go after git clone https://github.com/geek1011/BookBrowser.git
or I test with this command and I have an other error:
pip install git+https://github.com/geek1011/BookBrowser

This is my error:
"root@Dev:/usr/local # pip install git+https://github.com/geek1011/BookBrowser
Collecting git+https://github.com/geek1011/BookBrowser
  Cloning https://github.com/geek1011/BookBrowser to /tmp/pip-6hFyFG-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-6hFyFG-build/setup.py'
"
thanks

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-6hFyFG-build/

**Comment by geek1011** [comment]
It is written in go, not Python. Either download the prebuilt binaries from the releases page, or build it yourself with golang 1.9.
