### ISSUE TITLE
JPEG recreated at each start

### ISSUE THREAD

**Issue by SR-G** [geek1011/BookBrowser#33]
Even when defining a data dir, thumbnails are always recreated.

Steps to reproduce : 
- start program with the `--tempdir data/` flag
- all books are indexed / thumbnails are created
- stop the program, the log `2017/12/30 21:17:50 Not removing temp dir because dir already existed at start` is dumped (quite expected)
- data/ folder still contains all *.jpg
- start the program again with the same command line / same --tempdir
- everything is indexed again (maybe expected) but every single thumbnail is then also recreated (which takes quite some time with a lot of *.epub)

(a test like "if the corresponding cover and thumbbail jpeg are already available in the current tempdir, then don't recreate them" is probably missing)

With BookServer 3.0.4

**Comment by geek1011** [comment]
Thanks for reporting these issues!

As for caching, I forgot to add the check. Good catch.

**Comment by geek1011** [comment]
I have fixed this, and it will be included in the next release. As for performance, there is not much difference unless you have a large number of books.
