### ISSUE TITLE
Isolate the book repository update process (for "lazy start" and "manually triggering repository updates")

### ISSUE THREAD

**Issue by SR-G** [geek1011/BookBrowser#34]
Right now the repository scan seems to be done only on start.
The server is not going to start before the end of this analysis.

The idea would be to : isolate the scan process.

That would allow : 
- to have a "lazy start" : the server would immediately start while the analysis would be still on-going in the background
- to be able to manually trigger the refresh of the books repository while the server is up and running (for example through a dedicated UI function)

Would probably need to then have the status of this refresh on the UI ("Scan in progress, file # on #").

**Comment by geek1011** [comment]
That's a great idea. I'll look into implementing this sometime soon, once I have some more free time.

**Comment by geek1011** [comment]
I have implemented this and will be releasing it in the next version. Indexing will happen in the background with progress showing in the web interface and the terminal. A refresh can be triggered by sending SIGUSR1 to the process.

**Comment by geek1011** [comment]
@SR-G I've released this feature in v4.0.0.
