### ISSUE TITLE
[Error] Hyperlink cannot be jumped correctly

### ISSUE THREAD

**Issue by seuplus** [geek1011/BookBrowser#36]
The Hyperlinks in the epub book cannot be jumped to the corresponding page correctly. When I click anyone of the hyperlinks (see the `picture` below) it always jumps back to the cover of the book. 

But the hyperlinks can be jumped to the corresponding page correctly on my `Kindle Paper 3` and `Macbook's iBook`.

![screen shot 2018-01-06 at 19 34 25](https://user-images.githubusercontent.com/26323968/34639348-715d4438-f319-11e7-9830-3bf922762395.png)

**Comment by geek1011** [comment]
Ok. I think your ebook is using a url hash in the table of content. This is currently not supported in ePubViewer due to limitations of ePub.js. This might be fixed in a future release.
