### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by nasirkhan** [geek1011/BookBrowser#38]
Thanks for developing this awesome tool. 

I was planning to build a similar library system and eventually found your project. 

I would like to know if the user authentication is available here. My plan is to create an online library and users can read the books free of cost but they have to register first. Without the authentication users will not get the access to the books of the library.

**Comment by geek1011** [comment]
That is currently out of the scope of BookBrowser. You would probably want to put BookBrowser behind a reverse proxy with authentication (like caddy with the http.login plugin), or fork BookBrowser.
