### ISSUE TITLE
Iphone Flashing

### ISSUE THREAD

**Issue by orso081980** [geek1011/BookBrowser#39]
Is there any reason why, after developing it locally, on iPhone, both 6s and 10, the screen is flashing?

**Comment by orso081980** [comment]
My bad, I was implementing a framework with pub.js. I got confused, I will delete this topic. Sorry

**Comment by orso081980** [comment]
I don't think that I can actually cancel the issue. Could you do it for me? In the meantime, I will take advantage to ask you a question. I've never used golang, and I was trying to compile the code somewhere locally with a tool like node.js. Do you think it is possible to compile a code locally, using html, javascript and css using go and a compiler? Or could you explain to me how? Thank you for your time

**Comment by geek1011** [comment]
@orso081980 It's fine. 

As for compiling a golang app, you basically just download golang, set up the GOPATH environment variable, then `go get` the project to compile, or `go build` a local one.

**Comment by orso081980** [comment]
Could you be interested in doing some freelance job for my company? We are struggling in doing a project and we need a reliable reader for epub files. Bookbrowser is a fantastic solution but so far we haven't figured it out how to use it. We could be more than happy to hire you in helping us with this project.

Thank you in advance, we're looking forward to hearing from you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by orso081980** [comment]
Hey Patrick. How are you? What Do you think about my offer? Your reader is fantastic and we are really interested in your paid service. Please come back whenever you've got time. Have a good day

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
