### ISSUE TITLE
html5 problem

### ISSUE THREAD

**Issue by usafoi** [geek1011/BookBrowser#43]
I tried cordova run android,
OK run perfect BUT....
but apparently my phone cannot load the css and js it apppears to be hanging and crashed
it does says "your browser does not support ... "
yeah crazy right trying to make this runnable on android as hybrid? ehehe

**Comment by usafoi** [comment]
(thank you for replying) I am using lenovo P2, android 7.0  unfortunately I didn't update to latest system webview, currently  updating and I'll see if there's any changes.
> 
May I see a logcat from the browser
> 
and how to see logcat from my  phone? debugging?

**Comment by geek1011** [comment]
I'm going to close this issue for now.
