### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by eskwayrd** [geek1011/BookBrowser#44]
When I run BookBrowser in a folder with 6,955 books, once the indexer reaches 561 books, I start seeing this error:

```
2018/04/12 07:54:13 [561/6955] Error indexing /HumbleBundle E-books/SF and Fantasy/thelivesoftao.epub: open /HumbleBundle E-books/SF and Fantasy/thelivesoftao.epub: too many open files
``` 

This continues until processing reaches 1885 books and the process crashes.

I haven't investigated fully, but it seems like book files aren't being closed soon enough.

**Comment by eskwayrd** [comment]
It's not the book files themselves that are being held open too long, but the generated image thumbnails. Thumbnail filehandles need to be closed sooner than the end of all indexing operations.

I'll try to create a PR to fix this.

**Comment by geek1011** [comment]
OK. That sounds about right. Thanks for reporting this issue!

For now, you can increase the ulimit for open files.
