### ISSUE TITLE
Cannot execute `make` successfully

### ISSUE THREAD

**Issue by eskwayrd** [geek1011/BookBrowser#49]
I've tried running `make` a number of times, but I cannot seem to satisfy all of the missing dependencies.

I've added the following lines to the `Makefile`:
```
go get -v github.com/divan/autoreadme
go get -v github.com/stretchr/testify
go get -v github.com/davecgh/go-spew/spew
go get -v github.com/ernesto-jimenez/gogen
```
I had to also copy `stretchr/testify/_codegen` into the corresponding location in the `vendor` folder, but I haven't figured out how to satisfy the spew dependency, even after replacing spew in the `vendor` folder with a fresh copy of the entire package. Currently, when I run `make` I see:
```
$ make
rm -rf build BookBrowser
go get -v github.com/divan/autoreadme
go get -v github.com/stretchr/testify
go get -v github.com/davecgh/go-spew/spew
go get -v github.com/ernesto-jimenez/gogen
go get -v "github.com/kardianos/govendor"
go get -v "github.com/aktau/github-release"
go get -v github.com/jteeuwen/go-bindata/...
go get -v github.com/elazarl/go-bindata-assetfs/...
govendor sync
go generate ./...
2018/04/12 22:24:02 assertions.go:19:2: could not import github.com/davecgh/go-spew/spew (can't find import: github.com/eskwayrd/BookBrowser/vendor/github.com/davecgh/go-spew/spew)
exit status 1
vendor/github.com/stretchr/testify/assert/assertions.go:22: running "go": exit status 1
stat gen.go: no such file or directory
vendor/golang.org/x/net/html/atom/table.go:3: running "go": exit status 1
Makefile:25: recipe for target 'generate' failed
make: *** [generate] Error 1
```

Thoughts?

**Comment by geek1011** [comment]
I've never had this happen before. I think testify broke something. I'll see what I can do about this tomorrow.

**Comment by geek1011** [comment]
Does `go run bookbrowser.go` work?

**Comment by eskwayrd** [comment]
Heh. I just realized that on the machine I was trying to run `make`, the version of Go I had installed was 1.8. I upgraded to 1.10.1, and `make` completes successfully. I'll create a PR to update `README.md`.
