### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by BugHunterPhilosopher** [geek1011/BookBrowser#52]
Good evening,

I have A LOT OF books, so after scanning them for a while, BookBrowser throws:

Unknown error parsing book. Skipping. Error: runtime error: slice bounds out of range

**Comment by geek1011** [comment]
Can you send me a copy of the book which is mentioned before that error so I can have a look?

**Comment by geek1011** [comment]
OK. That seems like an issue extracting the metadata from the PDFs. The code I used for that is kind of hacky and does not work correctly for most PDFs.

I'll work on fixing this, but I don't completely understand the XMP metadata used in PDFs, so there's a limit to how much I'll be able to do. Thanks for reporting this issue!

**Comment by AlienQueen** [comment]
No worries. Thank you!

**Comment by geek1011** [comment]
Closing this for now.
