### ISSUE TITLE
Option to Disable iFrame

### ISSUE THREAD

**Issue by infosisio** [geek1011/BookBrowser#60]
This may not be trivial at all but this is a way to browse your books in your web browser and because of the iFrame you can't use all the goodies that the browser extensions have to offer.

**Comment by geek1011** [comment]
Which iframe?

**Comment by infosisio** [comment]
@geek1011 The viewer is displaying book contents in iframe.

**Comment by geek1011** [comment]
Oh, that. That's due to epub.js. There's nothing I can do about it, as it needs to be isolated from the app to prevent styling conflicts.
