### ISSUE TITLE
.dmg

### ISSUE THREAD

**Issue by jellytots1983** [geek1011/BookBrowser#63]
Do you support Mac? Would love to download. Thank you.

**Comment by geek1011** [comment]
Yes. It's the -darwin-64bit files in the releases page. Just download it, open a terminal, type `chmod +x `, drag the downloaded file over, and press enter. Then, drag the file over, type ` --bookdir `, and drag the folder with the books over and press enter.

**Comment by jellytots1983** [comment]
Hi

Thank you for this, as you can tell I’m not much of a techie! I’ve followed your instructions, but unfortunately it says permission denied. Never really used terminal before, is there a password my end I’m supposed to enter?

Thank you.
Emma

**Comment by geek1011** [comment]
Did you remember the `chmod` command?
