### ISSUE TITLE
Help on build issue

### ISSUE THREAD

**Issue by LiMinggang** [geek1011/BookBrowser#64]
I tried to build BookBrowser from scratch but met an error like below. Someone met the same issue with no answer. https://github.com/kardianos/govendor/issues/400
Any suggestion?

        govendor sync
Error: Package "C:\\dev\\BookBrowser" not a go package or not in GOPATH.
govendor sync
        Ensures the contents of the vendor folder matches the vendor file.
        Options:
                -n           dry run, print out action only
                -insecure    allow downloading over insecure connection
                -v           verbose output
NMAKE : fatal error U1077: 'C:\Users\gli\go\bin\govendor.EXE' : return code '0x2'
Stop.

**Comment by geek1011** [comment]
The vendor folder is checked in, so you can try not syncing it. As for the issue you are having, is your GOPATH set properly?

**Comment by LiMinggang** [comment]
Got the idea. I can build it now. 
Close the issue.
