### ISSUE TITLE
Server - related progress saving

### ISSUE THREAD

**Issue by zus0** [geek1011/BookBrowser#71]
The idea is that reading progress would be server related. For example, I'm reading some book on my PC, and I have to go somewhere. I take my phone, but progress would not be same as it is on the PC, and I have to remember, where did I stop.
Sorry for my bad English, I'm poor Russian kid.

**Comment by geek1011** [comment]
This is currently beyond the scope of BookBrowser. This would require adding server side storage for users and reading positions, as well as modifying ePubViewer. I may add sync to ePubViewer though if I can find an acceptable (client-side, free) storage mechanism.
