### ISSUE TITLE
launch it on apache webhost

### ISSUE THREAD

**Issue by Joduai** [geek1011/BookBrowser#77]
I've got maybe the most stupid question, but is it possible to launch this app on apache shared webhosting server?
I have no experience with go lang, just seen somewhere that there were some apache handlers for go, thus I'm curious.
Tried launching it within cgi-bin dir, but got only 500 error.

A simple "NO" answer will be good enough ;)

**Comment by geek1011** [comment]
I've never heard of an Apache handler for Go. Either way, this probably won't work on shared hosting.
