### ISSUE TITLE
Unable to clear old cached covers/thumbnails

### ISSUE THREAD

**Issue by dixonge** [geek1011/BookBrowser#87]
After going through my entire library and updating all metadata and cover images, restarting BookBrowser does not fix any missing or old cover images. Restarting the browser does not fix it either.

**Comment by geek1011** [comment]
Can you tell me which version you are using and  the full command used to start it?

**Comment by dixonge** [comment]
BookBrowser v 4.0.0

I specified the library and tempdir folders. I even deleted /tmp folders and all images in the tempdir - never took.

**Comment by geek1011** [comment]
How did you update the metadata/covers?

**Comment by dixonge** [comment]
Originally I didn't. I just let BookBrowser discover whatever cover it could and left it at that.

Most recently I used Calibre and manually downloaded the metadata and covers. Since these were embedded in the epub files I expected BookBrowser to discover these and update the covers, but it did not.

**Comment by geek1011** [comment]
Can you email me one of these books, and the old version if you still have it?

**Comment by geek1011** [comment]
Thanks, I received your email and took a look at the books. The issue is BookBrowser does not read Calibre's method of storing the OPF separately from the book itself, neither does it support reading an external cover. You need to use Calibre's `Polish Books` tool and select `Update metadata in the book files` to write the metadata to the epub file itself.

**Comment by dixonge** [comment]
Thanks - I was unaware of that feature! (it wasn't on the toolbar by default)

Ran 'polish' on all books. Cover images now integrated. It fixed the cover for In Patagonia. However, about 40% of my books, at least some of which have the cover image embedded in the epub file now, are still displaying 'no cover' - I'll keep exploring and see if I can find a difference between one of the working vs non-working covers.

**Comment by geek1011** [comment]
The difference is probably due to #30, which I'm planning to fix for the next version.

**Comment by dixonge** [comment]
This should have been closed a long time ago
