### ISSUE TITLE
Docker: how do I define one or several book directories

### ISSUE THREAD

**Issue by asitemade4u** [geek1011/BookBrowser#95]
Thank you for this very efficient book server!
I would prefer running it from docker and I have tried the docker file you provided.
But I could not find a way to tell the container to look into a directory where the books are located.
I tried to define a  `docker-compose` file but the `volume` instruction does not work.
Please help,
S.

**Comment by asitemade4u** [comment]
Also, is there a way to tell BookBrowser to look into directories recursively -- all  my books come from Calibre and thus they are embedded into directories.

**Comment by geek1011** [comment]
If you mount multiple volumes into subdirectories of /books, they should all be picked up.

**Comment by asitemade4u** [comment]
Thanks !

⁣S.​
